### PR TITLE
Use new method for RootCmd

### PR DESCRIPTION
**Pull request by tomkirkhawkeye**
This fixes compilation when targetting 7.x + versions of libbeat

### CODE REVIEW

**Comment by deepujain** [comment]
Thank you for PR. I verified the changes and they work with ES  7.2 
```
git clone https://github.com/elastic/beats ${GOPATH}/src/github.com/elastic/beats --branch 7.2
```

1. What do you want to do for users with ES < 7.x ?

**Comment by tomkirkhawkeye** [comment]
I wasn't really sure the best way to handle it, I'm not very familiar with go so not sure if there is some way we could branch at compile time depending on version? Any ideas?

**Comment by jerrac** [comment]
I was able to use tomkirkhawkeye:update-to-7.x to get nvidiagpubeat working on my local system. Thanks!

I'd suggest tagging a release for each version. So what I would do is tag where we're at now as v6.8.1 (or whatever version of https://github.com/elastic/beats you last tested nvidiagpubeat with) then merge this pull request in and tag it as v7.2.0.

Whenever breaking changes come in, add another tag. Just keep a table, or something, in the readme stating which tags should work with which versions of elastic/beats.

Or something like that. I'm not exactly experienced with versioning anything, so I'm just throwing out some ideas. :\

**Comment by deepujain** [comment]
@jerrac I like the idea of tagging for every version.

**Comment by deepujain** [comment]
https://github.com/eBay/nvidiagpubeat/pull/22 is the fix.

**Pull request closed without merging**
